import Head from 'next/head';
import Image from 'next/image';

import Component from '../components/login-btn';

export default function Home() {
  const handleClick = async () => {
    // console.log('clicked');

    const data = await fetch('/api/restricted', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    const json = await data.json();
    console.log(json);
  };

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='float-right'>
        <button onClick={() => handleClick()}>ServerSide Test</button>
        <br />
        <Component></Component>
      </div>

      <main className='main'>
        <h1 className='text-3xl font-bold underline text-primary'>
          Hello world!
        </h1>
      </main>

      <footer className='footer'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className='logo'>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
